server:
  port: 8989

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdatajpa
    username: root
    password: kumar

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create